### ISSUE TITLE
How to run the repo in to Android Studio. 

### ISSUE THREAD

**Issue by evrencoskun** [warren-bank/Android-NodeJS-Frontend#1]
Hi and thanks for the repo. 

Cloned the repo into my local machine and started to run my Android Studio. 

However, getting the below error. 

`A problem occurred configuring project ':NodeJS-Frontend'.`

What do I need to do so that I can get rid of this error and run the application in Android Studio?

Thanks

**Comment by warren-bank** [comment]
sufficed to say that a more detailed error log would be needed to properly diagnose your problem, here are a few quick thoughts:

* did you not load the ["android-studio-project"](https://github.com/warren-bank/Android-NodeJS-Frontend/tree/master/android-studio-project) directory as an existing Android Studio project?
* is `ndk` not installed on your system?

I haven't had the need to rebuild this project in a while, but I can assure you that it worked perfectly in the version of Android Studio that I was using at the time. It is possible (but unlikely) that a newer version of Android Studio will require minor tweaks.. such as an update to Gradle.. dunno. I'll run this test later..

**Comment by warren-bank** [comment]
here are my notes and observations when trying to open and build v1.0.1 of the project in 2x versions of Android Studio that I had in different virtual machine guest snapshots:

- - - -

```text
https://github.com/warren-bank/Android-NodeJS-Frontend/archive/refs/tags/v1.0.1.zip
https://github.com/warren-bank/Android-NodeJS-Frontend/blob/v1.0.1/android-studio-project/constants.gradle#L8
  - build tools: 30.0.3
https://github.com/warren-bank/Android-NodeJS-Frontend/blob/v1.0.1/android-studio-project/gradle/wrapper/gradle-wrapper.properties#L5
  - gradle 4.10.1
https://github.com/warren-bank/Android-NodeJS-Frontend/blob/v1.0.1/android-studio-project/build.gradle#L9
  - gradle wrapper 3.3.0

* Android Studio 3.3.2
  - build number: AI-182.5107.16.33.5314842
  - build date: 2019-02-15
  - platform tools 28.0.1
  - ndk 18.1.5063045
  - APK build status: success

* Android Studio 2020.3.1 patch 3
  - build number: AI-203.7717.56.2031.7784292
  - build date: 2021-09-30
  - platform tools 30.0.4
  - ndk 21.3.6528147
  - compatability issues:
    * older version of gradle expects ndk to be installed at:
        C:\Android\sdk\ndk-bundle
    * current version of Android Studio actually installs ndk at:
        C:\Android\sdk\ndk\21.3.6528147
    * workaround:
        mklink /J "C:\Android\sdk\ndk-bundle" "C:\Android\sdk\ndk\21.3.6528147"
    * manpage:
        https://ss64.com/nt/mklink.html
    * notes:
      - without this junction point,
        * project configuration does not fail
        * gradle causes Android Studio to reinstall ndk to the old path
  - APK build status: fail
    * error:
        Execution failed for task ':NodeJS-Frontend:externalNativeBuildRelease'.
        > Build command failed.
          Error while executing process C:\Android\sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build C:\workspace\android-studio-project\NodeJS-Frontend\.externalNativeBuild\cmake\release\x86_64 --target native-lib}
          [1/2] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o
          FAILED: C:\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=x86_64-none-linux-android21 --gcc-toolchain=C:/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=C:/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/sysroot  -Dnative_lib_EXPORTS -I../../../../libnode/include/node -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -O2 -DNDEBUG  -fPIC -MD -MT CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o -MF CMakeFiles\native-lib.dir\src\main\cpp\native-lib.cpp.o.d -o CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o -c C:\workspace\android-studio-project\NodeJS-Frontend\src\main\cpp\native-lib.cpp
          C:\workspace\android-studio-project\NodeJS-Frontend\src\main\cpp\native-lib.cpp:55:53: error: 'open' called with O_CREAT or O_TMPFILE, but missing mode
    * line of code causing error:
        int fd = open(filepath, O_CREAT|O_WRONLY|O_TRUNC);
    * at:
        https://github.com/warren-bank/Android-NodeJS-Frontend/blob/v1.0.1/android-studio-project/NodeJS-Frontend/src/main/cpp/native-lib.cpp#L55
    * cause:
        https://stackoverflow.com/questions/584210/unix-o-creat-flag-without-mode-specified
    * api reference:
        https://home.adelphi.edu/~pe16132/csc271/ppt/summaries/CPROGRAMMINGFILEIO.htm
        https://www.gnu.org/software/libc/manual/html_node/Permission-Bits.html
    * fix:
        int fd = open(filepath, O_CREAT|O_WRONLY|O_TRUNC, S_IRUSR|S_IWUSR);
    * equivalent fix:
        int fd = open(filepath, O_CREAT|O_WRONLY|O_TRUNC, 0600);
    * notes:
        "600" === (0x0400 | 0x0200).toString(16)
  - APK build status: success
```

**Comment by warren-bank** [comment]
I just pushed 2x commits..

1. commit [afd1200](https://github.com/warren-bank/Android-NodeJS-Frontend/commit/afd120021487ae607e7a6e9b66255ce8032cfd1e)
   * fixes the (aforementioned) line of code, so the project will compile using a recent version of ndk
   * still used very old build tools
2. commit [99aab9d](https://github.com/warren-bank/Android-NodeJS-Frontend/commit/99aab9de324e829a5ce308c011fc7d8499ca7de7)
   * updates build tools to use much newer versions
     - gradle 7.3.0
     - gradle wrapper 7.0.3
   * specifies explicit versions of build tools, as the new SxS feature allows multiple versions to coexist:
     - ndk 21.3.6528147
     - cmake 3.10.2.4988404

notes:
* target SDK is kept at 30 (Android 11) w/ SDK build tools 30.0.3
* I was debating increasing the target SDK to 31 (Android 12) w/ SDK build tools 31.0.0... in a 3rd commit
  - to do so would require a few additional changes to the [manifest](https://developer.android.com/guide/topics/manifest/activity-element#exported)
  - I opted to leave it alone (for now).. as I don't see any immediate need
* I also didn't see any reason to tag either of these commits, or publish new releases for them
  - the resulting APKs are functionally identical
  - I ran a few quick tests to confirm.. all good

**Comment by evrencoskun** [comment]
> did you not load the directory as an existing Android Studio project?

 I opened the  Android Studio project on my Android Studio. 

> is ndk not installed on your system?

No, It's not installed. 


OK thanks for your notes, I'll have a look at them.
